

apiVersion: v1
kind: Pod
metadata:
  name: second-pod
  labels:
    app: Nada
    label-name-1: label-value
    another-label: my-app-name

spec:
  containers:
    - image: nginx:alpine
      name: nginx-container
      ports:
        - containerPort: 80
      